### ISSUE TITLE
The code for Chemical Reaction Classification

### ISSUE THREAD

**Issue by HirahTang** [hwwang55/MolR#7]
Hi there! First of all, I wanted to say that I find your work very interesting and appreciate your contributions.

I noticed that you mentioned including chemical reaction classification as a downstream evaluation task for the model (3.3 of the paper), but I couldn't find this part of the code in the repository.

Would it be possible for you to provide more details about how you implemented this task?

**Comment by hwwang55** [comment]
Thanks for your interest in our work! This experiment was done later during the rebuttal stage. I forgot to push the code to here. But it is very similar to property prediction. You only need to concatenate [sum of reactant embeddings] and [sum of product embeddings], followed by an MLP with two 2048-dim hidden layers.

**Comment by HirahTang** [comment]
Thank you for the information!
