### ISSUE TITLE
Does the small batch size work?

### ISSUE THREAD

**Issue by hhhhzzzzz** [hwwang55/MolR#8]
Hi,
Thanks for your great work.

I'd like to know whether the small batch size (such as 16, 32, 64, etc.) works. 

Thanks!

**Comment by hwwang55** [comment]
Thanks for your interest in our work! Please look at Figure 5c for the results on batch size. Small batch sizes (32, 64) will harm the model performance (0.90 -> 0.84).

**Comment by hhhhzzzzz** [comment]
> Thanks for your interest in our work! Please look at Figure 5c for the results on batch size. Small batch sizes (32, 64) will harm the model performance (0.90 -> 0.84).

My apologies for overlooking this part. I've noticed that the required GPU memory increases as the batch size grows. It might be necessary for me to modify the code to accommodate a multi-GPU setup.
